utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

    
#Les routes pour CRUD Indicateur
dci_indicateur:
    resource: "@DciBundle/Resources/config/routing/indicateur.yml"
    prefix:   /indicateur
  
#Les routes pour CRUD Marchandise
dci_marchandise:
    resource: "@DciBundle/Resources/config/routing/marchandise.yml"
    prefix:   /marchandise
    
    
#Les routes pour CRUD SousCategorieEntite    
dci_souscategorieentite:
    resource: "@DciBundle/Resources/config/routing/souscategorieentite.yml"
    prefix:   /souscategorieentite
    
#Les routes pour CRUD indicaSousProdser     
dci_indicasousprodser:
    resource: "@DciBundle/Resources/config/routing/indicasousprodser.yml"
    prefix:   /indicasousprodser
    
#Les routes pour CRUD indicaProdser 
dci_indicaprodser:
    resource: "@DciBundle/Resources/config/routing/indicaprodser.yml"
    prefix:   /indicaprodser
    
#Les routes pour CRUD indicaProdser 
dci_categorieentite:
    resource: "@DciBundle/Resources/config/routing/categorieentite.yml"
    prefix:   /categorieentite
    
#Les routes pour CRUD indicateur marchandise
dci_indicamarcha:
    resource: "@DciBundle/Resources/config/routing/indicamarcha.yml"
    prefix:   /indicamarcha
    
#Les routes pour CRUD relever produid ou service
dci_relever:
    resource: "@DciBundle/Resources/config/routing/relever.yml"
    prefix:   /relever
    
#Les routes pour CRUD relever produid ou service
dci_arborescence:
    resource: "@DciBundle/Resources/config/routing/arborescence.yml"
    prefix:   /arborescence
 
#Les routes pour CRUD relever marchandise 
dci_relevermarchandise:
    resource: "@DciBundle/Resources/config/routing/relevermarchandise.yml"
    prefix:   /relevermarchandise

#Les routes pour CRUD relever sous produit ou service
dci_releversousprodser:
    resource: "@DciBundle/Resources/config/routing/releversousprodser.yml"
    prefix:   /releversousprodser

#Les routes pour CRUD les Oprateurs
dci_operateur:
    resource: "@DciBundle/Resources/config/routing/operateur.yml"
    prefix:   /operateur

#Les routes pour CRUD les Consommateurs   
dci_consommateur:
    resource: "@DciBundle/Resources/config/routing/consommateur.yml"
    prefix:   /consommateur
 
    #Les routes pour CRUD les Operateur Sous categories
dci_operatsouscateg:
    resource: "@DciBundle/Resources/config/routing/operatsouscateg.yml"
    prefix:   /operatsouscateg

    


app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin-dci
