<?php

namespace Utilisateur\UtilisateurBundle\Repository;

/**
 * CollecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
