<?php

namespace Utilisateur\UtilisateurBundle\Repository;

/**
 * DecideurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecideurRepository extends \Doctrine\ORM\EntityRepository
{
}
