<?php

namespace Utilisateur\UtilisateurBundle\Repository;

/**
 * ReleverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleverRepository extends \Doctrine\ORM\EntityRepository
{
}
