<?php

namespace Utilisateur\UtilisateurBundle\Repository;

/**
 * UserConnexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserConnexionRepository extends \Doctrine\ORM\EntityRepository
{
}
