utilisateur_homepage:
    path:     /
    defaults: { _controller: UtilisateurBundle:Default:index }
    
#Ajouter une nouvelle entité
utilisateur_entite:
    path:     /add-entite
    defaults: { _controller: UtilisateurBundle:Admin:addEtitite }
    
#Ajouter une nouvelle Categorie d'entité
utilisateur_categorie_entite:
    path:     /add-categorie-entite
    defaults: { _controller: UtilisateurBundle:Admin:addCategorieEtitite }
    
#Ajouter de nouvelles attributs d'entité
utilisateur_attribut_entite:
    path:     /add-attribut-entite/{id}
    defaults: { _controller: UtilisateurBundle:Admin:addAttributEtitite }
    
#Ajouter de nouvelles attributs de marchandise
utilisateur_attribut_marchandise:
    path:     /add-attribut-marchandise/{id}
    defaults: { _controller: UtilisateurBundle:Admin:addAttributMarchandise }
    
#Indicateur
utilisateur_indicateur:
    path:     /indicateur/{id}
    defaults: { _controller: UtilisateurBundle:Admin:indicateur }
    
#Relever d'indicateur
utilisateur_relever:
    path:     /relever/{id}
    defaults: { _controller: UtilisateurBundle:Admin:relever }
    
#Ajouter de nouvelles marchandise
utilisateur_marchandise:
    path:     /add-marchandise/{id}
    defaults: { _controller: UtilisateurBundle:Admin:addMarchandise }
    
    
    
#FOS_User   
utilisateur_teste:
    path:     /teste
    defaults: { _controller: UtilisateurBundle:Default:teste }
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
