<?php

namespace DCI\DciBundle\Repository;

/**
 * AttributEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
