<?php

namespace DCI\DciBundle\Repository;

/**
 * AttributMarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributMarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
}
