<?php

namespace DCI\DciBundle\Repository;

/**
 * CategorieEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEntiteRepository extends \Doctrine\ORM\EntityRepository
{
}
