<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ConsommateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsommateurRepository extends \Doctrine\ORM\EntityRepository {
    
     public function allConsommateurs($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('consommateur')
                ->select('consommateur')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
       public function allconsommateurLierAunMarchandise($page, $nbrAffichPage, $id) {
        $qb = $this->createQueryBuilder('consommateur')
                ->select('consommateur')
                ->leftJoin('consommateur.marchandise', 'marchandise')
                ->andWhere('marchandise.id =:id')
                ->setParameter('id', $id)
                ->orderBy('consommateur.id', 'DESC')
                ->getQuery();
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    
}
