<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntiteRepository extends \Doctrine\ORM\EntityRepository {
    
    public function allProduits($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('categorie')
                ->select('categorie')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
}
