<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * IndicateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicateurRepository extends \Doctrine\ORM\EntityRepository{
    
      public function allIndicateur($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder(' Indicateur')
                ->select(' Indicateur')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
      
    public function indicateurDunMarch($page, $nbrAffichPage, $idMarch) {
        $qb = $this->createQueryBuilder('indi')
                ->select('indi')
                ->leftJoin('indi.marchandise', 'marchandise')
                ->andWhere('marchandise.id =:id')
                ->setParameter('id', $idMarch)
                ->orderBy('indi.id', 'DESC')
                ->getQuery();
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    public function indicateurAll($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('indi')
                ->select('indi')
                ->orderBy('indi.id', 'DESC')
                ->getQuery();
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    
        public function lesIndiCaDepart($page, $nbrAffichPage, $idDepartema){
        
        $qb = $this->createQueryBuilder('indicat')
                ->select('indicat')
                ->leftJoin('indicat.departement', 'departement')
                ->andWhere('departement.id =:id')
                ->setParameter('id', $idDepartema)
                ->orderBy('indicat.id', 'DESC')
                ->getQuery();
        
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
        
}

