<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * IndicaSousProdSerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicaSousProdSerRepository extends \Doctrine\ORM\EntityRepository {
    
     public function allIndicaSousProdSer($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('IndicaSousProdSer')
                ->select('IndicaSousProdSer')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
          public function allIndicatD1SousCateg($id, $page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('IndicaSousProdSer')
                ->select('IndicaSousProdSer')
                ->leftJoin('IndicaSousProdSer.sousCateEntite', 'sousCateEntite')
                ->andWhere('sousCateEntite.id =:id')
                ->setParameter('id', $id)
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
}
