<?php

namespace DCI\DciBundle\Repository;

/**
 * IndicateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicateurRepository extends \Doctrine\ORM\EntityRepository
{
}
