<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarchandiseRepository extends \Doctrine\ORM\EntityRepository {
    
     public function allMarchandise($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('Marchandise')
                ->select('Marchandise')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
       public function marchtDunProduit($idproSer) {
        $qb = $this->createQueryBuilder('march')
                ->select('march')
                ->leftJoin('march.produitService', 'proSer')
                ->andWhere('proSer.id =:id')
                ->setParameter('id', $idproSer);

        return $qb->getQuery()->getResult();
    }
    
    public function marchandiseDunProduit($page, $nbrAffichPage, $idProduit) {
        $qb = $this->createQueryBuilder('march')
                ->select('march')
                ->leftJoin('march.entite', 'entite')
                ->andWhere('entite.id =:id')
                ->setParameter('id', $idProduit)
                ->orderBy('march.id', 'DESC')
                ->getQuery();
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    
}
