<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OperatSousCategRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatSousCategRepository extends \Doctrine\ORM\EntityRepository {
    
     public function allOperatSousCateg($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('operatSousCateg')
                ->select('operatSousCateg')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
    public function alloperatLierAUnProduit($page, $nbrAffichPage, $id) {
        $qb = $this->createQueryBuilder('operatSousCateg')
                ->select('operatSousCateg')
                ->leftJoin('operatSousCateg.sousCategEntite', 'sousCategEntite')
                ->andWhere('sousCategEntite.id =:id')
                ->setParameter('id', $id)
                ->orderBy('operatSousCateg.id', 'DESC')
                ->getQuery();
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    
}
