<?php

namespace DCI\DciBundle\Repository;

/**
 * ProduitServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
