<?php

namespace DCI\DciBundle\Repository;

/**
 * ReleverSousProdSerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleverSousProdSerRepository extends \Doctrine\ORM\EntityRepository
{
}
