<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleverRepository extends \Doctrine\ORM\EntityRepository {
    
    public function lesReleveDepart($page, $nbrAffichPage, $idDepartema){
        
        $qb = $this->createQueryBuilder('reveler')
                ->select('reveler')
                ->leftJoin('reveler.indicateur', 'indicateur')
                ->leftJoin('indicateur.departement', 'departement')
                ->andWhere('departement.id =:id')
                ->setParameter('id', $idDepartema)
                ->orderBy('reveler.id', 'DESC')
                ->getQuery();
        
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    
}
