<?php

namespace DCI\DciBundle\Repository;

/**
 * ReleverMarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleverMarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
}
