<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ReleverMarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleverMarchandiseRepository extends \Doctrine\ORM\EntityRepository {
    
    public function releversDunMarchandise($page, $nbrAffichPage, $id){
        
        $qb = $this->createQueryBuilder('ReleverMarchandise')
                ->select('ReleverMarchandise')
                ->leftJoin('ReleverMarchandise.indicaMarcha', 'indicaMarcha')
                ->leftJoin('indicaMarcha.marchandise', 'marchandise')
                ->andWhere('marchandise.id =:id')
                ->setParameter('id', $id)
                ->orderBy('ReleverMarchandise.id', 'DESC')
                ->getQuery();        
        $qb
           // On définit l'annonce à partir de laquelle commencer la liste
           ->setFirstResult(($page-1) * $nbrAffichPage)
           // Ainsi que le nombre d'annonce à afficher sur une page
           ->setMaxResults($nbrAffichPage) ;
            
            return new Paginator($qb, true);
    }
    
}
