<?php

namespace DCI\DciBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategorieEntiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieEntiteRepository extends \Doctrine\ORM\EntityRepository{
    
    public function allSousCategorieEntite($page, $nbrAffichPage) {
        $qb = $this->createQueryBuilder('SousCategorieEntite')
                ->select('SousCategorieEntite')
                ->getQuery();
        $qb
                // On définit l'annonce à partir de laquelle commencer la liste
                ->setFirstResult(($page - 1) * $nbrAffichPage)
                // Ainsi que le nombre d'annonce à afficher sur une page
                ->setMaxResults($nbrAffichPage);

        return new Paginator($qb, true);
    }
    
}
