easy_admin:
    site_name: 'DCI-ADMIN'
    formats:
        date:    'd/m/Y'
        time:    'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        max_results: 7
        
    entities:
        - Utilisateur\UtilisateurBundle\Entity\Admin
        - Utilisateur\UtilisateurBundle\Entity\Collecteur
        - Utilisateur\UtilisateurBundle\Entity\Decideur
        - Utilisateur\UtilisateurBundle\Entity\Gestionnaire
        - Utilisateur\UtilisateurBundle\Entity\InfoUser
        - Utilisateur\UtilisateurBundle\Entity\UserConnexion
        - DCI\DciBundle\Entity\Region
        - DCI\DciBundle\Entity\Departement

           